apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  # Mot de passe encodé en base64 (exemple: "superpassword" devient "c3VwZXJwYXNzd29yZA==")
  POSTGRES_PASSWORD: c3VwZXJwYXNzd29yZA==
